[debug] [2024-10-14T14:22:30.021Z] ----------------------------------------------------------------------
[debug] [2024-10-14T14:22:30.040Z] Command:       /usr/bin/node /usr/local/bin/firebase deploy
[debug] [2024-10-14T14:22:30.043Z] CLI Version:   13.4.1
[debug] [2024-10-14T14:22:30.046Z] Platform:      linux
[debug] [2024-10-14T14:22:30.048Z] Node Version:  v18.19.1
[debug] [2024-10-14T14:22:30.051Z] Time:          Mon Oct 14 2024 17:22:30 GMT+0300 (East Africa Time)
[debug] [2024-10-14T14:22:30.052Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-10-14T14:22:30.610Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-10-14T14:22:30.614Z] > authorizing via signed-in user (techhiracontact@gmail.com)
[debug] [2024-10-14T14:22:30.615Z] [iam] checking project own-my-data for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-10-14T14:22:30.631Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions [none]
[debug] [2024-10-14T14:22:30.632Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions x-goog-quota-user=projects/own-my-data
[debug] [2024-10-14T14:22:30.634Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2024-10-14T14:24:41.084Z] *** [apiv2] error from fetch(https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions, {"headers":{},"method":"POST","body":"{\"permissions\":[\"firebase.projects.get\",\"firebasehosting.sites.update\"]}"}): FetchError: request to https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions failed, reason: connect ETIMEDOUT 172.217.170.202:443
[debug] [2024-10-14T14:24:41.086Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions
[debug] [2024-10-14T14:24:41.092Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/own-my-data [none]
[debug] [2024-10-14T14:24:41.991Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/own-my-data 200
[debug] [2024-10-14T14:24:41.992Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/own-my-data {"projectId":"own-my-data","projectNumber":"1762464221","displayName":"own-my-data","name":"projects/own-my-data","resources":{"hostingSite":"own-my-data"},"state":"ACTIVE","etag":"1_56afa69a-a121-49a6-976c-56f54ccd9d2f"}
[info] 
[info] === Deploying to 'own-my-data'...
[info] 
[info] i  deploying hosting 
[debug] [2024-10-14T14:24:42.028Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/own-my-data/versions [none]
[debug] [2024-10-14T14:24:42.029Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/own-my-data/versions {"status":"CREATED","labels":{"deployment-tool":"cli-firebase"}}
[debug] [2024-10-14T14:26:52.150Z] *** [apiv2] error from fetch(https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/own-my-data/versions, {"headers":{},"method":"POST","body":"{\"status\":\"CREATED\",\"labels\":{\"deployment-tool\":\"cli-firebase\"}}"}): FetchError: request to https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/own-my-data/versions failed, reason: connect ETIMEDOUT 172.217.170.170:443
[debug] [2024-10-14T14:26:57.174Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
